
namespace jump {
/* Generated by tools/generate_audio.py. Host owns PCM playback. */
#ifndef JUMP3D_AUDIO_DATA_H_CPP
#define JUMP3D_AUDIO_DATA_H_CPP

#define J3_AUDIO_BANK(X) \
    X(SCALE_INTRO, 0u, 35367u, 0u) \
    X(SCALE_LOOP, 1u, 20000u, 1u) \
    X(SUCCESS, 2u, 3040u, 0u) \
    X(POP, 3u, 2465u, 0u) \
    X(COMBO1, 4u, 9440u, 0u) \
    X(COMBO2, 5u, 8480u, 0u) \
    X(COMBO3, 6u, 8800u, 0u) \
    X(COMBO4, 7u, 8800u, 0u) \
    X(COMBO5, 8u, 8480u, 0u) \
    X(COMBO6, 9u, 8480u, 0u) \
    X(COMBO7, 10u, 8160u, 0u) \
    X(COMBO8, 11u, 7520u, 0u) \
    X(FALL, 12u, 11360u, 0u) \
    X(FALL_2, 13u, 26400u, 0u) \
    X(START, 14u, 10720u, 0u) \
    X(SING, 15u, 215200u, 0u) \
    X(STORE, 16u, 74080u, 0u) \
    X(WATER, 17u, 70240u, 0u) \
    X(ICON, 18u, 44960u, 1u) \

static const j3_audio_clip_t j3_audio_bank[] = {
    {"assets/audio/scale_intro.s16", 35367u, 0u},
    {"assets/audio/scale_loop.s16", 20000u, 1u},
    {"assets/audio/success.s16", 3040u, 0u},
    {"assets/audio/pop.s16", 2465u, 0u},
    {"assets/audio/combo1.s16", 9440u, 0u},
    {"assets/audio/combo2.s16", 8480u, 0u},
    {"assets/audio/combo3.s16", 8800u, 0u},
    {"assets/audio/combo4.s16", 8800u, 0u},
    {"assets/audio/combo5.s16", 8480u, 0u},
    {"assets/audio/combo6.s16", 8480u, 0u},
    {"assets/audio/combo7.s16", 8160u, 0u},
    {"assets/audio/combo8.s16", 7520u, 0u},
    {"assets/audio/fall.s16", 11360u, 0u},
    {"assets/audio/fall_2.s16", 26400u, 0u},
    {"assets/audio/start.s16", 10720u, 0u},
    {"assets/audio/sing.s16", 215200u, 0u},
    {"assets/audio/store.s16", 74080u, 0u},
    {"assets/audio/water.s16", 70240u, 0u},
    {"assets/audio/icon.ogg", 44960u, 1u},
};

#define J3_AUDIO_CLIP_COUNT 19u
#define J3_AUDIO_CLIP_RATE_HZ 16000u

} // namespace jump
#endif
