/* Generated by tools/export_fonts.py from the original AA font header. */
#ifndef JUMP3D_FONT_METRICS_H_CPP
#define JUMP3D_FONT_METRICS_H_CPP

#include <stdint.h>

#include "jump3d_font.hpp"

namespace jump {

#define J3_FONT_TIERS 3u

/* ---- tier 0: compact ---- */

/* big_t0: 12 glyphs of 10x15 in 12 columns. */
#define J3_FONT_BIG_T0_GLYPHS "0123456789+-"


/* small_t0: 42 glyphs of 5x7 in 42 columns. */
#define J3_FONT_SMALL_T0_GLYPHS "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ:.-+/%"


/* cjk_t0: 13 glyphs of 12x12 in 13 columns. */
#define J3_FONT_CJK_T0_GLYPHS "本次得分最高重新开始很好快"



/* ---- tier 1: standard ---- */

/* big_t1: 12 glyphs of 20x30 in 12 columns. */
#define J3_FONT_BIG_T1_GLYPHS "0123456789+-"


/* small_t1: 42 glyphs of 8x11 in 32 columns. */
#define J3_FONT_SMALL_T1_GLYPHS "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ:.-+/%"


/* cjk_t1: 13 glyphs of 16x16 in 13 columns. */
#define J3_FONT_CJK_T1_GLYPHS "本次得分最高重新开始很好快"



/* ---- tier 2: large ---- */

/* big_t2: 12 glyphs of 27x41 in 9 columns. */
#define J3_FONT_BIG_T2_GLYPHS "0123456789+-"


/* small_t2: 42 glyphs of 11x15 in 23 columns. */
#define J3_FONT_SMALL_T2_GLYPHS "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ:.-+/%"


/* cjk_t2: 13 glyphs of 22x22 in 11 columns. */
#define J3_FONT_CJK_T2_GLYPHS "本次得分最高重新开始很好快"



static const j3_font_face_t j3_font_big_faces[J3_FONT_TIERS] = {
    {nullptr, J3_FONT_BIG_T0_GLYPHS, 10u, 15u, 12u, 120u, 15u},
    {nullptr, J3_FONT_BIG_T1_GLYPHS, 20u, 30u, 12u, 240u, 30u},
    {nullptr, J3_FONT_BIG_T2_GLYPHS, 27u, 41u, 9u, 243u, 82u},
};

static const j3_font_face_t j3_font_small_faces[J3_FONT_TIERS] = {
    {nullptr, J3_FONT_SMALL_T0_GLYPHS, 5u, 7u, 42u, 210u, 7u},
    {nullptr, J3_FONT_SMALL_T1_GLYPHS, 8u, 11u, 32u, 256u, 22u},
    {nullptr, J3_FONT_SMALL_T2_GLYPHS, 11u, 15u, 23u, 253u, 30u},
};

static const j3_font_face_t j3_font_cjk_faces[J3_FONT_TIERS] = {
    {nullptr, J3_FONT_CJK_T0_GLYPHS, 12u, 12u, 13u, 156u, 12u},
    {nullptr, J3_FONT_CJK_T1_GLYPHS, 16u, 16u, 13u, 208u, 16u},
    {nullptr, J3_FONT_CJK_T2_GLYPHS, 22u, 22u, 11u, 242u, 44u},
};

#define J3_FONT_MAX_ATLAS_BYTES_DATA 19926u

} // namespace jump
#endif
