#!/usr/bin/env python3
"""Generate the small-face RGB565 colors from the shipped lit textures."""
import argparse
import json
from pathlib import Path


def generate(app: Path) -> str:
    palette = json.loads((app / "resources/palette-lit.json").read_text())
    colors = []
    for slot in range(45):
        texels = (app / f"resources/b{slot:02d}.index8").read_bytes()
        # Each face can use lighting rows 0..6; keep their actual palette colors
        # instead of approximating the palette's gamma/shading on the CPU.
        for level in range(7):
            pixels = [palette[level * 256 + index] for index in texels if index]
            assert pixels
            count = len(pixels)
            r = (sum((v >> 11) & 31 for v in pixels) + count // 2) // count
            g = (sum((v >> 5) & 63 for v in pixels) + count // 2) // count
            b = (sum(v & 31 for v in pixels) + count // 2) // count
            colors.append((r << 11) | (g << 5) | b)
    lines = ["// Generated by tools/generate_lod_colors.py from resources; do not edit.",
             "#pragma once", "#include <array>", "#include <cstdint>",
             "namespace voxel {", "inline constexpr std::array<std::uint16_t, 45 * 7> kLodColors{{"]
    for slot in range(45):
        lines.append("    " + ", ".join(f"0x{v:04x}" for v in colors[slot * 7:slot * 7 + 7]) + ",")
    lines.extend(["}};", "} // namespace voxel", ""])
    return "\n".join(lines)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    app = Path(__file__).resolve().parent.parent
    target = app / "voxel_lod_colors.hpp"
    content = generate(app)
    if args.check:
        if not target.exists() or target.read_text() != content:
            parser.error("voxel_lod_colors.hpp is stale; run generate_lod_colors.py")
    else:
        target.write_text(content)
