#!/usr/bin/env python3
"""Generate the localized string tables and the anti-aliased font atlases.

Two INDEX8 atlases are emitted as coverage maps (0 = transparent, 255 =
opaque) so the renderer can draw text with the Host's per-texel alpha sprite
path:

    font_ascii  8x14 cells, 128x128 texture (16 columns x 9 rows)
    font_cjk    16x16 cells, 256x256 texture (16 columns x 16 rows)

Only the CJK characters actually used by tools/strings.py are baked in, which
keeps the atlas small enough for the panel and the Guest memory budget.

    python3 tools/generate_text.py
"""
import argparse
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

import strings

APP = Path(__file__).resolve().parents[1]

ASCII_CELL_W = 8
ASCII_CELL_H = 14
ASCII_COLS = 16
ASCII_ROWS = 9
ASCII_ATLAS_W = ASCII_CELL_W * ASCII_COLS
ASCII_ATLAS_H = ASCII_CELL_H * ASCII_ROWS

CJK_CELL = 16
CJK_COLS = 16
CJK_ROWS = 16
CJK_ATLAS = CJK_CELL * CJK_COLS

ASCII_FONT = '/usr/share/fonts/noto/NotoSansMono-Regular.ttf'
ASCII_FALLBACK = '/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf'
CJK_FONT = '/usr/share/fonts/adobe-source-han-sans/SourceHanSansCN-Regular.otf'
CJK_FALLBACK = '/usr/share/fonts/noto-cjk/NotoSansCJK-Regular.ttc'


def pick(primary, fallback):
    for path in (primary, fallback):
        if Path(path).exists():
            return path
    raise SystemExit('no font found: %s' % primary)


def draw_centered_glyph(cell, character, font, padding=0):
    draw = ImageDraw.Draw(cell)
    left, top, right, bottom = draw.textbbox((0, 0), character, font=font)
    width = right - left
    height = bottom - top
    x = (cell.width - width) // 2 - left
    y = (cell.height - height) // 2 - top
    if x + left < padding:
        x += padding - (x + left)
    if x + right > cell.width - padding:
        x -= x + right - (cell.width - padding)
    draw.text((x, y), character, font=font, fill=255)


def render_ascii():
    font = ImageFont.truetype(pick(ASCII_FONT, ASCII_FALLBACK), 11)
    atlas = bytearray(ASCII_ATLAS_W * ASCII_ATLAS_H)
    lookup = {}
    for code in range(0x20, 0x7F):
        slot = code - 0x20
        lookup[code] = slot
        cell = Image.new('L', (ASCII_CELL_W, ASCII_CELL_H), 0)
        draw_centered_glyph(cell, chr(code), font)
        pixels = cell.load()
        u = (slot % ASCII_COLS) * ASCII_CELL_W
        v = (slot // ASCII_COLS) * ASCII_CELL_H
        for y in range(ASCII_CELL_H):
            for x in range(ASCII_CELL_W):
                atlas[(v + y) * ASCII_ATLAS_W + u + x] = pixels[x, y]
    return atlas, lookup


def render_cjk(characters):
    font = ImageFont.truetype(pick(CJK_FONT, CJK_FALLBACK), 14)
    atlas = bytearray(CJK_ATLAS * CJK_ATLAS)
    lookup = {}
    if len(characters) > CJK_COLS * CJK_ROWS:
        raise SystemExit('too many CJK glyphs: %d' % len(characters))
    for slot, char in enumerate(characters):
        lookup[ord(char)] = slot
        cell = Image.new('L', (CJK_CELL, CJK_CELL), 0)
        draw_centered_glyph(cell, char, font, 1)
        pixels = cell.load()
        u = (slot % CJK_COLS) * CJK_CELL
        v = (slot // CJK_COLS) * CJK_CELL
        for y in range(CJK_CELL):
            for x in range(CJK_CELL):
                atlas[(v + y) * CJK_ATLAS + u + x] = pixels[x, y]
    return atlas, lookup


def emit_byte_array(name, data, width=24):
    lines = []
    for offset in range(0, len(data), width):
        chunk = data[offset:offset + width]
        lines.append('    ' + ','.join(str(value) for value in chunk) + ',')
    return 'const uint8_t %s[%d] = {\n%s\n};\n' % (name, len(data), '\n'.join(lines))


def emit_strings():
    header = ['/* Generated by tools/generate_text.py -- do not edit. */',
              '#ifndef PD_STRINGS_H',
              '#define PD_STRINGS_H', '',
              '#include <stdint.h>', '',
              'typedef enum {']
    for entry in strings.STRINGS:
        header.append('    %s,' % strings.c_identifier(entry[0]))
    header.append('    PD_STR_COUNT')
    header.append('} pd_string_id_t;')
    header.append('')
    header.append('void pd_strings_set_language(uint8_t chinese);')
    header.append('uint8_t pd_strings_chinese(void);')
    header.append('const char *pd_str(pd_string_id_t id);')
    header.append('/* Formats %s and %d placeholders into out. */')
    header.append('void pd_str_format(char *out, int capacity, pd_string_id_t id, ...);')
    header.append('/* Writes an item name plus its upgrade suffix. */')
    header.append('void pd_str_item(char *out, int capacity, pd_string_id_t id,')
    header.append('                int upgrade_level);')
    header.append('')
    header.append('#endif')

    body = ['/* Generated by tools/generate_text.py -- do not edit. */',
            '#include "strings.h"', '',
            'typedef struct { const char *en; const char *zh; } pd_string_t;',
            '',
            'static const pd_string_t kStrings[PD_STR_COUNT] = {']
    for entry in strings.STRINGS:
        body.append('    {%s, %s},' % (_c_string(entry[1]), _c_string(entry[2])))
    body.append('};')
    body.append('')
    body.append('static uint8_t g_chinese;')
    body.append('')
    body.append('void pd_strings_set_language(uint8_t chinese) { g_chinese = chinese != 0; }')
    body.append('uint8_t pd_strings_chinese(void) { return g_chinese; }')
    body.append('const char *pd_str(pd_string_id_t id) {')
    body.append('    if (id >= PD_STR_COUNT) id = PD_STR_ENTER_DUNGEON;')
    body.append('    return g_chinese ? kStrings[id].zh : kStrings[id].en;')
    body.append('}')
    body.append('')
    body.append(FORMAT_IMPLEMENTATION)
    return '\n'.join(header) + '\n', '\n'.join(body).rstrip('\n') + '\n'


def _c_string(text):
    """Escapes a Python string into a C literal (UTF-8 bytes)."""
    out = ['"']
    for byte in text.encode('utf-8'):
        if byte == 0x22:
            out.append('\\"')
        elif byte == 0x5C:
            out.append('\\\\')
        elif 0x20 <= byte < 0x7F:
            out.append(chr(byte))
        else:
            out.append('\\x%02x' % byte)
            out.append('""')
    out.append('"')
    return ''.join(out)


FORMAT_IMPLEMENTATION = '''
#include <stdarg.h>

static char *format_append(char *out, char *end, const char *text) {
    while (*text != '\\0' && out < end) *out++ = *text++;
    return out;
}

static char *format_uint(char *out, char *end, int value) {
    char digits[12];
    int count = 0;
    unsigned int magnitude;
    if (value < 0) {
        if (out < end) *out++ = '-';
        magnitude = (unsigned int)(-value);
    } else {
        magnitude = (unsigned int)value;
    }
    if (magnitude == 0) {
        if (out < end) *out++ = '0';
        return out;
    }
    while (magnitude > 0 && count < 11) {
        digits[count++] = (char)('0' + magnitude % 10u);
        magnitude /= 10u;
    }
    while (count > 0 && out < end) *out++ = digits[--count];
    return out;
}

/* Substitutes %s (char *) and %d (int) in the localized string. */
void pd_str_format(char *out, int capacity, pd_string_id_t id, ...) {
    const char *format = pd_str(id);
    char *cursor = out;
    char *end = out + capacity - 1;
    va_list arguments;
    if (capacity <= 0) return;
    va_start(arguments, id);
    while (*format != '\\0' && cursor < end) {
        if (*format == '%' && (format[1] == 's' || format[1] == 'd')) {
            if (format[1] == 's') {
                cursor = format_append(cursor, end, va_arg(arguments, const char *));
            } else {
                cursor = format_uint(cursor, end, va_arg(arguments, int));
            }
            format += 2;
            continue;
        }
        *cursor++ = *format++;
    }
    va_end(arguments);
    *cursor = '\\0';
}

void pd_str_item(char *out, int capacity, pd_string_id_t id, int upgrade_level) {
    char *cursor = out;
    char *end = out + capacity - 1;
    const char *name = pd_str(id);
    if (capacity <= 0) return;
    cursor = format_append(cursor, end, name);
    if (upgrade_level > 0 && cursor < end) {
        *cursor++ = ' ';
        *cursor++ = '+';
        cursor = format_uint(cursor, end, upgrade_level);
    }
    *cursor = '\\0';
}
'''


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    parser.add_argument('--preview')
    args = parser.parse_args()

    characters = strings.chinese_characters()
    ascii_atlas, _ = render_ascii()
    cjk_atlas, _ = render_cjk(characters)
    header, body = emit_strings()

    if args.preview:
        image = Image.new('RGB', (max(ASCII_ATLAS_W, CJK_ATLAS),
                                  ASCII_ATLAS_H + CJK_ATLAS), (20, 20, 30))
        pixels = image.load()
        for y in range(ASCII_ATLAS_H):
            for x in range(ASCII_ATLAS_W):
                value = ascii_atlas[y * ASCII_ATLAS_W + x]
                pixels[x, y] = (value, value, value)
        for y in range(CJK_ATLAS):
            for x in range(CJK_ATLAS):
                value = cjk_atlas[y * CJK_ATLAS + x]
                pixels[x, ASCII_ATLAS_H + y] = (value, value, value)
        image.resize((image.width * 3, image.height * 3),
                     Image.NEAREST).save(args.preview)
        print('wrote %s (%d CJK glyphs)' % (args.preview, len(characters)))
        return

    font_header = ['/* Generated by tools/generate_text.py -- do not edit. */',
                   '#ifndef PD_FONT_DATA_H',
                   '#define PD_FONT_DATA_H', '',
                   '#include <stdint.h>', '',
                   '#define PD_ASCII_CELL_W %d' % ASCII_CELL_W,
                   '#define PD_ASCII_CELL_H %d' % ASCII_CELL_H,
                   '#define PD_ASCII_ATLAS_W %d' % ASCII_ATLAS_W,
                   '#define PD_ASCII_ATLAS_H %d' % ASCII_ATLAS_H,
                   '#define PD_CJK_CELL %d' % CJK_CELL,
                   '#define PD_CJK_ATLAS_W %d' % CJK_ATLAS,
                   '#define PD_CJK_ATLAS_H %d' % CJK_ATLAS,
                   '#define PD_CJK_GLYPHS %d' % len(characters), '',
                   'extern const uint8_t pd_font_ascii[PD_ASCII_ATLAS_W * PD_ASCII_ATLAS_H];',
                   'extern const uint8_t pd_font_cjk[PD_CJK_ATLAS_W * PD_CJK_ATLAS_H];',
                   '/* Slot of a CJK codepoint, or -1 when it is not baked in. */',
                   'int pd_font_cjk_slot(uint32_t codepoint);',
                   '', '#endif']
    font_body = ['/* Generated by tools/generate_text.py -- do not edit. */',
                 '#include "font_data.h"', '',
                 emit_byte_array('pd_font_ascii', ascii_atlas),
                 emit_byte_array('pd_font_cjk', cjk_atlas)]
    font_body.append('static const uint32_t kCjkCodepoints[PD_CJK_GLYPHS] = {')
    for offset in range(0, len(characters), 8):
        chunk = characters[offset:offset + 8]
        font_body.append('    ' + ','.join('0x%04x' % ord(c) for c in chunk) + ',')
    font_body.append('};')
    font_body.append('')
    font_body.append('int pd_font_cjk_slot(uint32_t codepoint) {')
    font_body.append('    int low = 0;')
    font_body.append('    int high = PD_CJK_GLYPHS - 1;')
    font_body.append('    while (low <= high) {')
    font_body.append('        const int middle = (low + high) / 2;')
    font_body.append('        const uint32_t value = kCjkCodepoints[middle];')
    font_body.append('        if (value == codepoint) return middle;')
    font_body.append('        if (value < codepoint)')
    font_body.append('            low = middle + 1;')
    font_body.append('        else')
    font_body.append('            high = middle - 1;')
    font_body.append('    }')
    font_body.append('    return -1;')
    font_body.append('}')

    outputs = [
        ('strings.h', header),
        ('strings.c', body),
        ('font_data.h', '\n'.join(font_header) + '\n'),
        ('font_data.c', '\n'.join(font_body) + '\n'),
    ]
    for filename, content in outputs:
        target = APP / filename
        if args.check:
            if not target.exists() or target.read_text() != content:
                raise SystemExit('%s is out of date' % filename)
            print('%s ok' % filename)
        else:
            target.write_text(content)
            print('wrote %s' % target)
    print('strings=%d cjk_glyphs=%d' % (len(strings.STRINGS), len(characters)))


if __name__ == '__main__':
    main()
