#!/usr/bin/env python3
"""Generate the Pixel Dungeon audio banks from Shattered Pixel Dungeon.

The PXA audio service accepts 16 kHz mono signed 16-bit PCM frames, and no
platform decodes Ogg/MP3 assets, so the Guest synthesises everything itself.
This script decodes the original sounds with ffmpeg, trims and downsamples
them, and emits compact 8-bit PCM tables (audio.c/audio.h) that the mixer
expands to 16-bit frames at runtime.

Usage:
    python3 tools/generate_audio.py --spd-assets /path/to/shattered-pixel-dungeon
"""
import argparse
import json
import os
import subprocess
import sys
from pathlib import Path

APP = Path(__file__).resolve().parents[1]
RATE = 16000
MUSIC_RATE = 8000

# SPD sound file -> (C name, maximum seconds, gain in Q8 dB)
SOUNDS = [
    ('hit', 'HIT', 0.27, -3),
    ('miss', 'MISS', 0.21, -6),
    ('hit_crush', 'HIT_STRONG', 0.30, -3),
    ('death', 'DEATH', 0.54, -3),
    ('drink', 'DRINK', 0.42, -4),
    ('eat', 'EAT', 0.42, -5),
    ('gold', 'GOLD', 0.36, -5),
    ('descend', 'DESCEND', 0.84, -3),
    ('door_open', 'DOOR', 0.42, -6),
    ('trap', 'TRAP', 0.30, -3),
    ('levelup', 'LEVELUP', 0.96, -3),
    ('item', 'ITEM', 0.30, -6),
    ('read', 'READ', 0.42, -6),
    ('shatter', 'SHATTER', 0.48, -4),
    ('unlock', 'UNLOCK', 0.36, -4),
    ('health_warn', 'HUNGRY', 0.36, -6),
    ('step', 'STEP', 0.24, -8),
    ('grass', 'GRASS', 0.30, -7),
    ('trample', 'TRAMPLE', 0.36, -6),
    ('water', 'WATER', 0.36, -7),
]

# One looping music bed per region band, trimmed to a short loop.
MUSIC = [
    ('sewers_1.ogg', 'SEWERS', 6.0),
    ('prison_1.ogg', 'PRISON', 6.0),
    ('caves_1.ogg', 'CAVES', 6.0),
    ('city_1.ogg', 'CITY', 6.0),
    ('halls_1.ogg', 'HALLS', 6.0),
]


def decode(path, rate, seconds, channels=1):
    """Decodes a compressed file to 8-bit unsigned mono PCM at `rate`."""
    command = [
        'ffmpeg', '-v', 'error', '-i', str(path),
        '-t', '%.3f' % seconds,
        '-ac', str(channels), '-ar', str(rate),
        '-f', 'u8', '-',
    ]
    result = subprocess.run(command, stdout=subprocess.PIPE, check=True)
    return result.stdout


def emit_array(name, data):
    lines = []
    for offset in range(0, len(data), 24):
        chunk = data[offset:offset + 24]
        lines.append('    ' + ','.join(str(value) for value in chunk) + ',')
    return 'const uint8_t %s[%d] = {\n%s\n};\n' % (name, len(data), '\n'.join(lines))


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--spd-assets', default=os.environ.get('PXA_SPD_ASSETS'))
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    if not args.spd_assets:
        raise SystemExit('pass --spd-assets /path/to/shattered-pixel-dungeon')
    spd = Path(args.spd_assets) / 'core/src/main/assets'
    if not (spd / 'sounds').is_dir():
        raise SystemExit('not a Shattered Pixel Dungeon checkout: %s' % spd)

    header = ['/* Generated by tools/generate_audio.py from Shattered Pixel',
              ' * Dungeon audio. Shattered Pixel Dungeon (C) 2014-2026 Evan',
              ' * Debenham, GPL-3.0. 8-bit unsigned mono PCM. */',
              '#ifndef PD_AUDIO_DATA_H',
              '#define PD_AUDIO_DATA_H', '',
              '#include <stdint.h>', '',
              '#define PD_SFX_RATE %d' % RATE,
              '#define PD_MUSIC_RATE %d' % MUSIC_RATE, '',
              'enum {']
    body = ['/* Generated by tools/generate_audio.py -- do not edit. */',
            '#include "audio_data.h"', '']
    entries = []
    sound_assets = {}

    for source, name, seconds, gain in SOUNDS:
        path = spd / 'sounds' / (source + '.mp3')
        if not path.exists():
            raise SystemExit('missing sound: %s' % path)
        pcm = decode(path, RATE, seconds)
        sound_assets[source] = pcm
        entries.append((name, gain, len(pcm)))
        header.append('    PD_SFX_%s = %d,' % (name, len(entries) - 1))
        body.append(emit_array('pd_sfx_%s' % name.lower(), pcm))
    header.append('    PD_SFX_COUNT = %d' % len(entries))
    header.append('};')
    header.append('')
    header.append('typedef struct { const uint8_t *pcm; uint32_t bytes; '
                  'int16_t gain_db_q8; } pd_sfx_bank_t;')
    header.append('extern const pd_sfx_bank_t pd_sfx_bank[PD_SFX_COUNT];')
    header.append('')
    header.append('enum {')
    music_entries = []
    for source, name, seconds in MUSIC:
        path = spd / 'music' / source
        if not path.exists():
            raise SystemExit('missing music: %s' % path)
        pcm = decode(path, MUSIC_RATE, seconds)
        music_entries.append((name, len(pcm)))
        header.append('    PD_MUSIC_%s = %d,' % (name, len(music_entries) - 1))
        body.append(emit_array('pd_music_%s' % name.lower(), pcm))
    header.append('    PD_MUSIC_COUNT = %d' % len(music_entries))
    header.append('};')
    header.append('')
    header.append('typedef struct { const uint8_t *pcm; uint32_t bytes; } '
                  'pd_music_bank_t;')
    header.append('extern const pd_music_bank_t pd_music_bank[PD_MUSIC_COUNT];')
    header.append('')
    header.append('#endif')
    body.append('const pd_sfx_bank_t pd_sfx_bank[PD_SFX_COUNT] = {')
    for name, gain, size in entries:
        body.append('    {pd_sfx_%s, %d, %d},' % (name.lower(), size, gain * 256))
    body.append('};')
    body.append('const pd_music_bank_t pd_music_bank[PD_MUSIC_COUNT] = {')
    for name, size in music_entries:
        body.append('    {pd_music_%s, %d},' % (name.lower(), size))
    body.append('};')

    header_text = '\n'.join(header) + '\n'
    body_text = '\n'.join(body) + '\n'
    for filename, content in (('audio_data.h', header_text),
                              ('audio_data.c', body_text)):
        target = APP / filename
        if args.check:
            if not target.exists() or target.read_text() != content:
                raise SystemExit('%s is out of date' % filename)
            print('%s ok' % filename)
        else:
            target.write_text(content)
            print('wrote %s (%d bytes)' % (target, len(content)))
    for asset_root in (APP / 'assets', APP / 'assets-esp32s3'):
        sound_root = asset_root / 'sfx'
        if not args.check:
            sound_root.mkdir(parents=True, exist_ok=True)
        for source, pcm in sound_assets.items():
            target = sound_root / (source + '.pcm')
            if args.check:
                if not target.exists() or target.read_bytes() != pcm:
                    raise SystemExit('%s is out of date' % target)
            else:
                target.write_bytes(pcm)
    print('sfx=%d music=%d' % (len(entries), len(music_entries)))


if __name__ == '__main__':
    main()
