#!/usr/bin/env python3
"""Export the existing AA coverage atlases byte-for-byte for Host binding.

The full authored header remains the native pixel reference. The Guest keeps
only glyph metrics; the package compiler wraps raw INDEX8 files as PXR assets.
No resampling, quantization or font substitution is performed.
"""
from pathlib import Path
import hashlib,json,re

root=Path(__file__).resolve().parents[1]
source=(root/'jump3d_font_data.hpp').read_text()
resources=root/'resources';resources.mkdir(exist_ok=True)
entries=[]
pattern=r'static const uint8_t (j3_font_\w+_t\d_pixels)\[(\d+)u \* (\d+)u\] = \{([^}]+)\};'
def export(match):
    name,width,height,body=match.groups();width=int(width);height=int(height)
    pixels=bytes(int(n) for n in re.findall(r'\b\d+\b',body))
    assert len(pixels)==width*height
    filename=name.removesuffix('_pixels')
    (resources/(filename+'.index8')).write_bytes(pixels)
    entries.append({'path':'assets/fonts/'+filename+'.pxr','kind':'index8',
        'source':'resources/'+filename+'.index8','width':width,'height':height})
    print(filename,len(pixels),hashlib.sha256(pixels).hexdigest())
    return ''
metrics=re.sub(pattern,export,source)
assert len(entries)==9
metrics=metrics.replace('JUMP3D_FONT_DATA_H_CPP','JUMP3D_FONT_METRICS_H_CPP')
metrics=metrics.replace('/* Generated by tools/generate_fonts.py - do not edit by hand. */',
    '/* Generated by tools/export_fonts.py from the original AA font header. */')
metrics=re.sub(r'\bj3_font_\w+_t\d_pixels\b','nullptr',metrics)
(root/'jump3d_font_metrics.hpp').write_text(metrics)
(root/'resources.json').write_text(json.dumps({'assets':entries},indent=2)+'\n')
