/* Generated by tools/generate_audio.py from Shattered Pixel
 * Dungeon audio. Shattered Pixel Dungeon (C) 2014-2026 Evan
 * Debenham, GPL-3.0. 8-bit unsigned mono PCM. */
#ifndef PD_AUDIO_DATA_H
#define PD_AUDIO_DATA_H

#include <stdint.h>

#define PD_SFX_RATE 16000
#define PD_MUSIC_RATE 8000

enum {
    PD_SFX_HIT = 0,
    PD_SFX_MISS = 1,
    PD_SFX_HIT_STRONG = 2,
    PD_SFX_DEATH = 3,
    PD_SFX_DRINK = 4,
    PD_SFX_EAT = 5,
    PD_SFX_GOLD = 6,
    PD_SFX_DESCEND = 7,
    PD_SFX_DOOR = 8,
    PD_SFX_TRAP = 9,
    PD_SFX_LEVELUP = 10,
    PD_SFX_ITEM = 11,
    PD_SFX_READ = 12,
    PD_SFX_SHATTER = 13,
    PD_SFX_UNLOCK = 14,
    PD_SFX_HUNGRY = 15,
    PD_SFX_STEP = 16,
    PD_SFX_GRASS = 17,
    PD_SFX_TRAMPLE = 18,
    PD_SFX_WATER = 19,
    PD_SFX_COUNT = 20
};

typedef struct { const uint8_t *pcm; uint32_t bytes; int16_t gain_db_q8; } pd_sfx_bank_t;
extern const pd_sfx_bank_t pd_sfx_bank[PD_SFX_COUNT];

enum {
    PD_MUSIC_SEWERS = 0,
    PD_MUSIC_PRISON = 1,
    PD_MUSIC_CAVES = 2,
    PD_MUSIC_CITY = 3,
    PD_MUSIC_HALLS = 4,
    PD_MUSIC_COUNT = 5
};

typedef struct { const uint8_t *pcm; uint32_t bytes; } pd_music_bank_t;
extern const pd_music_bank_t pd_music_bank[PD_MUSIC_COUNT];

#endif
