/* Generated by tools/generate_text.py -- do not edit. */
#ifndef PD_FONT_DATA_H
#define PD_FONT_DATA_H

#include <stdint.h>

#define PD_ASCII_CELL_W 8
#define PD_ASCII_CELL_H 14
#define PD_ASCII_ATLAS_W 128
#define PD_ASCII_ATLAS_H 126
#define PD_CJK_CELL 16
#define PD_CJK_ATLAS_W 256
#define PD_CJK_ATLAS_H 256
#define PD_CJK_PAGE_GLYPHS 256
#define PD_CJK_EXTRA_ATLAS_H 48
#define PD_CJK_EXTRA_GLYPHS 46
#define PD_CJK_GLYPHS 302

extern const uint8_t pd_font_ascii[PD_ASCII_ATLAS_W * PD_ASCII_ATLAS_H];
extern const uint8_t pd_font_cjk[PD_CJK_ATLAS_W * PD_CJK_ATLAS_H];
extern const uint8_t pd_font_cjk_extra[PD_CJK_ATLAS_W * PD_CJK_EXTRA_ATLAS_H];
/* Slot of a CJK codepoint, or -1 when it is not baked in. */
int pd_font_cjk_slot(uint32_t codepoint);

#endif
