#!/usr/bin/env python3
"""Compile the existing deterministic generator offline; Guest keeps metrics only.

No Pillow/font dependency is required: font pixels come from the checked-in
generate_fonts.py output. Run this after changing that output or block_textures.c.
"""
import json
import os
from pathlib import Path
import re
import struct
import subprocess
import tempfile

APP = Path(__file__).resolve().parents[1]


def main():
    with tempfile.TemporaryDirectory(prefix="voxel-resources-") as tmp:
        binary = Path(tmp) / "export"
        subprocess.run([os.environ.get("CC", "cc"), "-std=c99", "-O2",
                        str(APP / "tools/export_resources.c"),
                        str(APP / "block_textures.c"), "-lm", "-o", str(binary)], check=True)
        data = subprocess.check_output([str(binary)])
    resources = APP / "resources"
    resources.mkdir(exist_ok=True)
    assets = []
    cursor = 512

    def texture(name, width, height, payload):
        assert len(payload) == width * height
        (resources / (name + ".index8")).write_bytes(payload)
        assets.append(dict(kind="index8", source=f"resources/{name}.index8",
                           path=f"assets/{name}.pxr", width=width, height=height))

    for slot in range(45):
        texture(f"b{slot:02}", 16, 16, data[cursor:cursor + 256])
        cursor += 256
    font_header = (APP / "voxel_font_data.h").read_text()
    definitions = re.findall(r"^#define (VOXEL_FONT_\w+) (.+)$", font_header, re.M)
    macros = dict(definitions)
    for tier, label in enumerate(("SMALL", "MEDIUM", "LARGE")):
        values = [int(macros[f"VOXEL_FONT_{label}_{field}"].removesuffix("u"))
                  for field in ("WIDTH", "HEIGHT", "COLUMNS", "ROWS")]
        width, height = values[0] * values[2], values[1] * values[3]
        size = width * height
        texture(f"font{tier}", width, height, data[cursor:cursor + size])
        cursor += size
    assert cursor == len(data)
    (APP / "voxel_font_metrics.h").write_text(
        "/* Generated by tools/generate_resources.py; no pixel arrays. */\n"
        "#ifndef VOXEL_FONT_METRICS_H\n#define VOXEL_FONT_METRICS_H\n" +
        "".join(f"#define {name} {value}\n" for name, value in definitions) + "#endif\n")

    # Legacy cut-out font is cheap in storage and is loaded only if AA is absent.
    rows = json.loads((APP / "resources/legacy-font-rows.json").read_text())
    legacy = bytearray(168 * 5)
    assert len(rows) == 42
    for glyph, bits in enumerate(rows):
        for y, row in enumerate(bits):
            for x in range(3):
                if row & (4 >> x): legacy[y * 168 + glyph * 4 + x] = 255
    texture("font-legacy", 168, 5, legacy)

    base = struct.unpack("<256H", data[:512])
    def shade(color, intensity):
        def channel(value):
            value = value * intensity + 127
            return (value + 1 + ((value + 1) >> 8)) >> 8
        return channel(color >> 11) << 11 | channel((color >> 5) & 63) << 5 | channel(color & 31)
    lit = [shade(color, (15 - level) * 255 // 15) for level in range(16) for color in base]
    for name, colors in (("palette", base), ("palette-lit", lit)):
        (resources / (name + ".json")).write_text(json.dumps(colors) + "\n")
        assets.append(dict(kind="palette", source=f"resources/{name}.json", path=f"assets/{name}.pxr"))
    (APP / "resources.json").write_text(json.dumps({"assets": assets}, indent=2) + "\n")
    print(f"Generated {len(assets)} independent resources; source pixels {len(data)} bytes")


if __name__ == "__main__":
    main()
